"""Automatically change date to DATE and rename duration to hours

Revision ID: 3845bd07838b
Revises: adf30122d8f9
Create Date: 2024-08-30 09:49:41.982000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3845bd07838b'
down_revision = 'adf30122d8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.DOUBLE_PRECISION(), nullable=False, server_default="0.0"))
        batch_op.alter_column('date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DATE(),
               existing_nullable=False)

        batch_op.alter_column('hours', server_default=None)

        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('hours')
