"""Change duration column to Float

Revision ID: adf30122d8f9
Revises: 915ae2a097b7
Create Date: 2024-08-28 16:14:57.027228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adf30122d8f9'
down_revision = '915ae2a097b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
                postgresql_using='duration::double precision')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    # ### end Alembic commands ###
